### PR TITLE
Quote reserved SQL words

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/Electron100/butane/issues/102

https://github.com/Electron100/butane/pull/105 should be merged first.

Notes:
- I dont mind if you want the `String` version - commit 1. Or squash in the `Cow<str>`.
- It would be useful to add specific tests for the new function, but it is getting a *lot* of coverage.

### CODE REVIEW

**Comment by Electron100** [comment]
Thank you for this fix. But why not just always quote identifiers? Then we could avoid the new dependency or having multiple cases to worry about. I haven't measured, but given the array lookup and the upcase, I would guess that trying to figure out whether a given identifier needs to be quoted or not will be slower than just always quoting, and we could put the quotes directly in the `write!` macro invocations to avoid any more allocation than is already happening.

I feel as though I'm probably missing something there....

**Comment by jayvdb** [comment]
> I would guess that trying to figure out whether a given identifier needs to be quoted or not will be slower than just always quoting

I guess so as well.

The only reason I can give is that unnecessary quotes is harder for humans to read.

Two places where this turns up is

1. the raw up/down SQL files.  If they are being reviewed by a human, having quotes appear only on reserved words gives reviewers a hint that the name of those columns are likely to be a source of bugs in the future, and maybe it is better to rename the struct member name now before the change is approved.  Avoiding tech debt.
2. error logs are easier to read if there isnt a lot of unnecessary quoting.  The error handler often will be using `{:?}` on objects within the error message, which adds a layer of quotes  as seen at https://github.com/Electron100/butane/issues/102, and often the error handler will also be doing `blah blah: \"{:?}\"` adds another set of quotes for the brain to contend with.

(1) can be kept by only using `quote_reserved_word()` in DDL.  The overhead shouldn't be a problem for offline once-off activities like generating the migrations.

If the runtime performance hit is a problem, then I would prefer to put the extra dependency & `quote_reserved_word()` behind a feature, so butane always quotes if the feature is not enabled.

**Comment by jayvdb** [comment]
We can also copy `sqlparser::keywords::ALL_KEYWORDS` into butane.  The description at https://docs.rs/sqlparser/latest/sqlparser/keywords/index.html suggests this list is too broad and should be trimmed.

**Comment by Electron100** [comment]
Keeping the up/down sql files more readable is fair. 
I realized belatedly after trying it out, that always quoting the runtime operations while not quoting the sql files (unless necessary) doesn't work due to the case normalization of unquoted identifiers, as mentioned in section 4.1.1 here https://www.postgresql.org/docs/current/sql-syntax-lexical.html](url).

I don't love the performance hit of the linear array search here, but since this fixes an issue with correctness, I'm going to go ahead and merge it as-is then try to speed it up in a following change.

**Comment by jayvdb** [comment]
ah, we should probably capitalise the words that are being quoted.

**Comment by Electron100** [comment]
The Postgres documentation notes that it folds unquoted identifiers to lower-case rather than upper-case as specified by the standard. So if we were to anticipate the case folding rules we'd need to make more of the sql logic db-specific.

**Pull request merged**
